name=TextFinder
version=2.2.1
author=Michael Margolis
maintainer=Paul Gallagher <gallagher.paul@gmail.com>
sentence=Arduino library for extracting information from a stream of data.
paragraph=Designed for use used with the Arduino Ethernet library to find particular fields and get strings or numeric values. It can also be used with Serial data.
category=Data Processing
url=https://github.com/tardate/TextFinder
architectures=*
